"""Command-line interface: ``clean-code check``, ``config-template``, ``rules``."""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path

import click

from cleancode.config import Config, ConfigError, RuleConfig
from cleancode.engine import analyze_paths
from cleancode.models import CheckResult, Severity, Violation
from cleancode.rules.base import ProjectRule, Rule

_SEVERITY_COLORS = {
    Severity.INFO: "cyan",
    Severity.WARNING: "yellow",
    Severity.ERROR: "red",
}


@dataclass(frozen=True)
class CheckOptions:
    """The ``check`` command's flags, grouped so the command itself takes one param."""

    as_json: bool
    config_path: Path | None
    select: str | None
    ignore: str | None
    no_suppress: bool
    fail_on: str | None
    min_severity: str | None


@click.group()
@click.version_option(package_name="clean-code")
def main() -> None:
    """Enforce human-readable Python — especially code generated by LLMs."""


@main.command()
@click.argument(
    "paths", nargs=-1, required=True, type=click.Path(exists=True, path_type=Path)
)
@click.option("--json", "as_json", is_flag=True, help="Emit machine-readable JSON.")
@click.option(
    "--config",
    "config_path",
    type=click.Path(exists=True, path_type=Path),
    help="Explicit TOML config file (default: nearest pyproject.toml).",
)
@click.option(
    "--select", help="Comma-separated rule ids to run exclusively (e.g. ST101,CM302)."
)
@click.option("--ignore", help="Comma-separated rule ids to skip.")
@click.option(
    "--no-suppress", is_flag=True, help="Ignore inline `# cleancode: disable` comments."
)
@click.option(
    "--fail-on",
    type=click.Choice(["info", "warning", "error"]),
    help="Lowest severity that causes a non-zero exit (default from config).",
)
@click.option(
    "--min-severity",
    default=None,
    type=click.Choice(["info", "warning", "error"]),
    help="Lowest severity to display (default from config, itself default "
    "'warning'). Pass 'info' to opt in to the lowest-signal noise.",
)
def check(paths: tuple[Path, ...], **kwargs: object) -> None:
    """Analyze Python files and report readability violations."""
    options = CheckOptions(**kwargs)
    try:
        config = Config.load(paths[0], override=options.config_path)
        _apply_rule_filters(config, options.select, options.ignore)
    except (ConfigError, ValueError) as error:
        raise click.UsageError(str(error)) from error
    config.honor_suppressions = not options.no_suppress
    if options.fail_on is not None:
        config.fail_on = Severity.from_name(options.fail_on)
        config.fail_on_explicit = True
    if options.min_severity is not None:
        config.min_severity = Severity.from_name(options.min_severity)
        config.min_severity_explicit = True
    if config.fail_on_explicit and not config.min_severity_explicit:
        # An explicit fail_on with no min_severity means the user cares about
        # that severity; don't let the default min_severity hide it from view.
        config.min_severity = config.fail_on

    file_results = analyze_paths(list(paths), config)
    if options.as_json:
        shown_results = _filter_by_severity(file_results, config.min_severity)
        shown_results = [
            file_result
            for file_result in shown_results
            if file_result.violations or file_result.parse_error
        ]
        click.echo(
            json.dumps(
                [file_result.to_dict() for file_result in shown_results], indent=2
            )
        )
    else:
        _print_human(file_results, config.min_severity)

    sys.exit(_exit_code(file_results, config.fail_on))


@main.command("config-template")
@click.option(
    "--out",
    "out_path",
    type=click.Path(path_type=Path),
    help="Write the template to a file instead of stdout.",
)
def config_template(out_path: Path | None) -> None:
    """Print a commented reference config listing every rule and its options."""
    from cleancode.template import build_config_template

    text = build_config_template()
    if out_path is not None:
        out_path.write_text(text, encoding="utf-8")
        click.echo(f"wrote {out_path}", err=True)
    else:
        click.echo(text, nl=False)


@main.command()
@click.argument(
    "path", default=".", type=click.Path(exists=True, path_type=Path)
)
@click.option(
    "--config",
    "config_path",
    type=click.Path(exists=True, path_type=Path),
    help="Explicit TOML config file (default: nearest pyproject.toml).",
)
@click.option(
    "--agents-md",
    "as_agents_md",
    is_flag=True,
    help="Wrap the brief with standing instructions for a CLAUDE.md/AGENTS.md file.",
)
def guide(path: Path, config_path: Path | None, as_agents_md: bool) -> None:
    """Print a generation-time brief: write Python this way the first time."""
    from cleancode.guide import build_agents_md, build_guide

    try:
        config = Config.load(path, override=config_path)
    except (ConfigError, ValueError) as error:
        raise click.UsageError(str(error)) from error
    text = build_agents_md(config) if as_agents_md else build_guide(config)
    click.echo(text, nl=False)


@main.command()
@click.argument("rule_ids", nargs=-1, required=True)
@click.option(
    "--config",
    "config_path",
    type=click.Path(exists=True, path_type=Path),
    help="Explicit TOML config file (default: nearest pyproject.toml).",
)
def explain(rule_ids: tuple[str, ...], config_path: Path | None) -> None:
    """Show a rule's description, guidance, and a BAD/GOOD example."""
    from cleancode.rules import RULES_BY_ID

    unknown = [rule_id for rule_id in rule_ids if rule_id not in RULES_BY_ID]
    if unknown:
        valid = ", ".join(sorted(RULES_BY_ID))
        raise click.UsageError(
            f"unknown rule id(s) {', '.join(unknown)}; valid ids: {valid}"
        )

    try:
        config = Config.load(Path.cwd(), override=config_path)
    except (ConfigError, ValueError) as error:
        raise click.UsageError(str(error)) from error

    for index, rule_id in enumerate(rule_ids):
        if index:
            click.echo()
        _print_explanation(rule_id, config)


def _print_explanation(rule_id: str, config: Config) -> None:
    from cleancode.examples import EXAMPLES
    from cleancode.rules import RULES_BY_ID

    rule = RULES_BY_ID[rule_id]
    rule_config = config.rules[rule_id]
    status = "enabled" if rule_config.enabled else "disabled"
    header = f"{rule.id}  {rule.name}  [{rule_config.severity.name.lower()}]  ({status})"
    click.echo(click.style(header, bold=True))
    click.echo(f"  {rule.description}\n")
    if rule.guidance is not None:
        click.echo(f"  guidance: {rule.guidance.format(**rule_config.options)}\n")
    _print_options(rule, rule_config)
    example = EXAMPLES[rule_id]
    click.echo("  # BAD")
    _print_snippet(example.bad)
    click.echo("  # GOOD")
    _print_snippet(example.good)
    if example.note:
        click.echo(f"\n  {example.note}")


def _print_options(rule: type[Rule] | type[ProjectRule], rule_config: RuleConfig) -> None:
    if not rule.default_options:
        return
    click.echo("  options:")
    for option, default in rule.default_options.items():
        current = rule_config.options.get(option, default)
        marker = "default" if current == default else f"configured (default {default!r})"
        click.echo(f"    {option} = {current!r}  [{marker}]")
    click.echo()


_SNIPPET_HEAD = 6
_SNIPPET_TAIL = 4
_SNIPPET_TRUNCATE_ABOVE = 14


def _print_snippet(code: str) -> None:
    lines = code.splitlines()
    if len(lines) <= _SNIPPET_TRUNCATE_ABOVE:
        for line in lines:
            click.echo(f"  {line}")
        return
    omitted = len(lines) - _SNIPPET_HEAD - _SNIPPET_TAIL
    for line in lines[:_SNIPPET_HEAD]:
        click.echo(f"  {line}")
    click.echo(f"  ... ({omitted} lines omitted) ...")
    for line in lines[-_SNIPPET_TAIL:]:
        click.echo(f"  {line}")


@main.command()
def rules() -> None:
    """List every rule with its default threshold and severity."""
    from cleancode.rules import ALL_RULES

    for rule in ALL_RULES:
        defaults = ", ".join(
            f"{key}={value}" for key, value in rule.default_options.items()
        )
        header = f"{rule.id}  {rule.name}"
        click.echo(
            f"{click.style(header, bold=True)}  "
            f"[{rule.default_severity.name.lower()}]  ({defaults})"
        )
        click.echo(f"    {rule.description}\n")


def _apply_rule_filters(config: Config, select: str | None, ignore: str | None) -> None:
    if select:
        _apply_select(config, select)
    if ignore:
        _apply_ignore(config, ignore)


def _apply_select(config: Config, select: str) -> None:
    selected = {rule_id.strip() for rule_id in select.split(",")}
    unknown = selected - config.rules.keys()
    if unknown:
        raise ConfigError(f"--select: unknown rule id(s) {', '.join(sorted(unknown))}")
    for rule_id, rule_config in config.rules.items():
        rule_config.enabled = rule_id in selected


def _apply_ignore(config: Config, ignore: str) -> None:
    for rule_id in (part.strip() for part in ignore.split(",")):
        if rule_id not in config.rules:
            raise ConfigError(f"--ignore: unknown rule id {rule_id}")
        config.rules[rule_id].enabled = False


def _filter_by_severity(
    file_results: list[CheckResult], min_severity: Severity
) -> list[CheckResult]:
    # Display-only: the exit code is computed separately and ignores this filter.
    return [
        CheckResult(
            path=file_result.path,
            violations=[
                violation
                for violation in file_result.violations
                if violation.severity >= min_severity
            ],
            parse_error=file_result.parse_error,
        )
        for file_result in file_results
    ]


def _print_human(file_results: list[CheckResult], min_severity: Severity) -> None:
    counts = {severity: 0 for severity in Severity}
    for file_result in file_results:
        _print_file_result(file_result, counts, min_severity)
    _print_summary(file_results, counts, min_severity)


def _print_file_result(
    file_result: CheckResult, counts: dict[Severity, int], min_severity: Severity
) -> None:
    if file_result.parse_error:
        click.echo(f"{file_result.path}: {click.style(file_result.parse_error, fg='red')}")
        return
    for violation in file_result.violations:
        counts[violation.severity] += 1
    shown = [
        violation
        for violation in file_result.violations
        if violation.severity >= min_severity
    ]
    if not shown:
        return
    click.echo(f"{file_result.path}:")
    for violation in shown:
        _print_violation(violation)


def _print_violation(violation: Violation) -> None:
    severity_label = click.style(
        violation.severity.name.lower(), fg=_SEVERITY_COLORS[violation.severity]
    )
    click.echo(
        f"  {violation.line}:{violation.col}: {severity_label} "
        f"{violation.rule_id} {violation.message}"
    )
    if violation.suggestion:
        click.echo(f"      fix: {violation.suggestion}")


def _print_summary(
    file_results: list[CheckResult],
    counts: dict[Severity, int],
    min_severity: Severity,
) -> None:
    total = sum(counts.values())
    files = len(file_results)
    if total == 0 and not any(file_result.parse_error for file_result in file_results):
        click.echo(click.style(f"✓ {files} file(s) clean", fg="green"))
        return
    click.echo(
        f"\n{total} violation(s) in {files} file(s): "
        f"{counts[Severity.ERROR]} error(s), {counts[Severity.WARNING]} warning(s), "
        f"{counts[Severity.INFO]} info(s)"
    )
    hidden = sum(count for severity, count in counts.items() if severity < min_severity)
    if hidden:
        click.echo(
            f"({hidden} hidden below --min-severity {min_severity.name.lower()}; "
            "pass a lower --min-severity to see them)"
        )


def _exit_code(file_results: list[CheckResult], fail_on: Severity) -> int:
    if any(file_result.parse_error for file_result in file_results):
        return 2
    worst = max(
        (
            violation.severity
            for file_result in file_results
            for violation in file_result.violations
        ),
        default=None,
    )
    return 1 if worst is not None and worst >= fail_on else 0
