"""Command-line interface: ``cleancode check``, ``cleancode rules``, ``cleancode generate``."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import click

from cleancode.config import Config, ConfigError
from cleancode.engine import analyze_path
from cleancode.models import CheckResult, Severity

_SEVERITY_COLORS = {Severity.INFO: "cyan", Severity.WARNING: "yellow", Severity.ERROR: "red"}


@click.group()
@click.version_option(package_name="cleancode")
def main() -> None:
    """Enforce human-readable Python — especially code generated by LLMs."""


@main.command()
@click.argument("paths", nargs=-1, required=True, type=click.Path(exists=True, path_type=Path))
@click.option("--json", "as_json", is_flag=True, help="Emit machine-readable JSON.")
@click.option("--config", "config_path", type=click.Path(exists=True, path_type=Path), help="Explicit TOML config file (default: nearest pyproject.toml).")
@click.option("--select", help="Comma-separated rule ids to run exclusively (e.g. ST101,CM302).")
@click.option("--ignore", help="Comma-separated rule ids to skip.")
@click.option("--no-suppress", is_flag=True, help="Ignore inline `# cleancode: disable` comments.")
@click.option("--fail-on", type=click.Choice(["info", "warning", "error"]), help="Lowest severity that causes a non-zero exit (default from config).")
def check(  # cleancode: disable=ST104
    paths: tuple[Path, ...],
    as_json: bool,
    config_path: Path | None,
    select: str | None,
    ignore: str | None,
    no_suppress: bool,
    fail_on: str | None,
) -> None:
    """Analyze Python files and report readability violations."""
    try:
        config = Config.load(paths[0], override=config_path)
        _apply_rule_filters(config, select, ignore)
    except (ConfigError, ValueError) as error:
        raise click.UsageError(str(error)) from error
    if fail_on is not None:
        config.fail_on = Severity.from_name(fail_on)

    file_results: list[CheckResult] = []
    for path in paths:
        file_results.extend(analyze_path(path, config, honor_suppressions=not no_suppress))

    if as_json:
        click.echo(json.dumps([file_result.to_dict() for file_result in file_results], indent=2))
    else:
        _print_human(file_results)

    sys.exit(_exit_code(file_results, config.fail_on))


@main.command()
def rules() -> None:
    """List every rule with its default threshold and severity."""
    from cleancode.rules import ALL_RULES

    for rule in ALL_RULES:
        defaults = ", ".join(f"{key}={value}" for key, value in rule.default_options.items())
        header = f"{rule.id}  {rule.name}"
        click.echo(
            f"{click.style(header, bold=True)}  "
            f"[{rule.default_severity.name.lower()}]  ({defaults})"
        )
        click.echo(f"    {rule.description}\n")


@main.command()
@click.argument("task")
@click.option("--out", "out_path", type=click.Path(path_type=Path), help="Write the final code to a file instead of stdout.")
@click.option("--model", default="claude-sonnet-5", show_default=True, help="Anthropic model id.")
@click.option("--max-iterations", default=3, show_default=True, help="Refinement rounds after the initial generation.")
@click.option("--show-iterations", is_flag=True, help="Print each iteration's code to stderr, not just its violation count.")
def generate(
    task: str,
    out_path: Path | None,
    model: str,
    max_iterations: int,
    show_iterations: bool,
) -> None:
    """Generate code for TASK with an LLM, re-prompting until it passes all rules."""
    from cleancode.llm import AnthropicClient, generate_clean_code

    config = Config.load(Path.cwd())
    client = AnthropicClient(model=model)
    generation = generate_clean_code(task, client, config, max_iterations=max_iterations)

    for index, iteration in enumerate(generation.iterations):
        status = (
            "clean"
            if iteration.check_result.ok
            else f"{len(iteration.check_result.violations)} violation(s)"
        )
        if iteration.check_result.parse_error:
            status = f"syntax error ({iteration.check_result.parse_error})"
        click.echo(f"iteration {index}: {status}", err=True)
        if show_iterations:
            click.echo(iteration.code, err=True)

    click.echo(f"stopped: {generation.stop_reason}", err=True)
    if out_path is not None:
        out_path.write_text(generation.code + "\n", encoding="utf-8")
        click.echo(f"wrote {out_path}", err=True)
    else:
        click.echo(generation.code)
    sys.exit(0 if generation.clean else 1)


def _apply_rule_filters(config: Config, select: str | None, ignore: str | None) -> None:
    if select:
        selected = {rule_id.strip() for rule_id in select.split(",")}
        unknown = selected - config.rules.keys()
        if unknown:
            raise ConfigError(f"--select: unknown rule id(s) {', '.join(sorted(unknown))}")
        for rule_id, rule_config in config.rules.items():
            rule_config.enabled = rule_id in selected
    if ignore:
        for rule_id in (part.strip() for part in ignore.split(",")):
            if rule_id not in config.rules:
                raise ConfigError(f"--ignore: unknown rule id {rule_id}")
            config.rules[rule_id].enabled = False


def _print_human(file_results: list[CheckResult]) -> None:
    total = 0
    counts = {severity: 0 for severity in Severity}
    for file_result in file_results:
        if file_result.parse_error:
            click.echo(
                f"{file_result.path}: "
                f"{click.style('syntax error', fg='red')}: {file_result.parse_error}"
            )
            continue
        for violation in file_result.violations:
            total += 1
            counts[violation.severity] += 1
            severity_label = click.style(
                violation.severity.name.lower(), fg=_SEVERITY_COLORS[violation.severity]
            )
            location = f"{file_result.path}:{violation.line}:{violation.col}"
            click.echo(
                f"{location}: {severity_label} {violation.rule_id} "
                f"[{violation.rule_name}] {violation.message}"
            )
            if violation.suggestion:
                click.echo(f"    fix: {violation.suggestion}")

    files = len(file_results)
    if total == 0 and not any(file_result.parse_error for file_result in file_results):
        click.echo(click.style(f"✓ {files} file(s) clean", fg="green"))
    else:
        click.echo(
            f"\n{total} violation(s) in {files} file(s): "
            f"{counts[Severity.ERROR]} error(s), {counts[Severity.WARNING]} warning(s), "
            f"{counts[Severity.INFO]} info(s)"
        )


def _exit_code(file_results: list[CheckResult], fail_on: Severity) -> int:
    if any(file_result.parse_error for file_result in file_results):
        return 2
    worst = max(
        (
            violation.severity
            for file_result in file_results
            for violation in file_result.violations
        ),
        default=None,
    )
    return 1 if worst is not None and worst >= fail_on else 0
